prepare-openvpn: Switch to watching for config.json changes in order to update the VPN config
The watching works by having the config-json.path trigger the config-json.service every time the config.json file changes, and as the prepare-openvpn.service has a `WantedBy=config-json.service` it will therefore also be triggered by it.  As config-json.service also has a `WantedBy=mnt-boot.mount` it means it will also trigger once on boot, and hence trigger the prepare-openvpn.service once on boot as well, allowing for the case of subsequent boots.

diff --git a/meta-resin-common/recipes-connectivity/openvpn/openvpn/prepare-openvpn b/meta-resin-common/recipes-connectivity/openvpn/openvpn/prepare-openvpn
--- a/meta-resin-common/recipes-connectivity/openvpn/openvpn/prepare-openvpn
+++ b/meta-resin-common/recipes-connectivity/openvpn/openvpn/prepare-openvpn
@@ -12,19 +12,15 @@ if [ ! -f $CONFIG_PATH ]; then
 	exit 1
 fi
 
-while :; do
-	_uuid=$(jq -r '.uuid' $CONFIG_PATH)
-	# If the user api key exists we use it instead of the deviceApiKey as it means we haven't done the key exchange yet
-	_device_api_key=$(jq -r '.apiKey // .deviceApiKey' $CONFIG_PATH)
+_uuid=$(jq -r '.uuid' $CONFIG_PATH)
+# If the user api key exists we use it instead of the deviceApiKey as it means we haven't done the key exchange yet
+_device_api_key=$(jq -r '.apiKey // .deviceApiKey' $CONFIG_PATH)
 
-	if [ "$_uuid" = "null" ] || [ "$_device_api_key" = "null" ]; then
-		echo "prepare-openvpn: UUID and/or APIKEY missing from config file, VPN cannot connect"
-		sleep 2
-	else
-		echo $_uuid > /var/volatile/vpnfile
-		echo $_device_api_key >> /var/volatile/vpnfile
-		break
-	fi
-done
+if [ "$_uuid" = "null" ] || [ "$_device_api_key" = "null" ]; then
+	echo "prepare-openvpn: UUID and/or APIKEY missing from config file, VPN cannot connect"
+	exit 1
+fi
 
+echo $_uuid > /var/volatile/vpnfile
+echo $_device_api_key >> /var/volatile/vpnfile
 sed -e "/remote .*/ c\remote $VPN_ENDPOINT $_vpn_port" /etc/openvpn/resin.conf > /run/openvpn/resin.conf
